
import React, { useState } from 'react';
import Page from '../components/Page';
import Card from '../components/Card';
import { riskAssessmentData, districts } from '../data/mockData';

interface DownloadItemProps {
  title: string;
  format: string;
  icon: string;
  onDownload: () => void;
}

const DownloadItem: React.FC<DownloadItemProps> = ({ title, format, icon, onDownload }) => {
  const [isDownloading, setIsDownloading] = useState(false);

  const handleClick = async () => {
    setIsDownloading(true);
    // Simulate async operation or wait for the actual download function
    await onDownload();
    setTimeout(() => setIsDownloading(false), 1000); // Keep loading state briefly visible
  };

  return (
    <div className="bg-gray-700 p-4 rounded-lg flex items-center justify-between hover:bg-gray-600 transition-colors">
      <div className="flex items-center">
        <span className="text-3xl mr-4">{icon}</span>
        <div>
          <h4 className="font-semibold text-white">{title}</h4>
          <p className="text-sm text-gray-400">{format}</p>
        </div>
      </div>
      <button
        onClick={handleClick}
        disabled={isDownloading}
        className={`font-bold py-2 px-4 rounded-lg transition-all ${
          isDownloading
            ? 'bg-gray-500 text-gray-300 cursor-wait'
            : 'bg-teal-600 hover:bg-teal-700 text-white'
        }`}
      >
        {isDownloading ? 'Generating...' : 'Download'}
      </button>
    </div>
  );
};

const Reports: React.FC = () => {

  // Helper to trigger download of a Blob
  const triggerDownload = (content: string, fileName: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // 1. Generate CSV
  const handleCSVDownload = () => {
    const headers = ['District ID', 'Name', 'Population', 'Risk Level', 'Hazard Score', 'Vulnerability Index', 'Risk Score'];
    const rows = riskAssessmentData.map(d => [
      d.id,
      d.name,
      d.population,
      d.riskLevel,
      d.hazardScore,
      d.vulnerabilityIndex,
      d.riskScore?.toFixed(4) || '0'
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');

    triggerDownload(csvContent, 'India_DRR_Risk_Scores.csv', 'text/csv');
  };

  // 2. Generate GeoJSON
  const handleGeoJSONDownload = () => {
    const geoJSON = {
      type: "FeatureCollection",
      features: districts.map(d => ({
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [d.lng, d.lat]
        },
        properties: {
          name: d.name,
          riskLevel: d.riskLevel,
          population: d.population,
          riskScore: d.riskScore
        }
      }))
    };
    
    triggerDownload(JSON.stringify(geoJSON, null, 2), 'India_Hazard_Layers.geojson', 'application/geo+json');
  };

  // 3. Mock Generators for PDF, PNG, Shapefile (simulated delay)
  const handleMockDownload = (fileName: string) => {
    return new Promise<void>((resolve) => {
      setTimeout(() => {
        // Create a dummy text file to represent the complex report
        const dummyContent = `
INDIA DRR SYSTEM REPORT
=======================
File: ${fileName}
Generated: ${new Date().toLocaleString()}

This is a placeholder file for the ${fileName}. 
In a production environment, this would be a binary file generated by the backend server.

Summary Statistics:
-------------------
Total Districts: ${riskAssessmentData.length}
High Risk Zones: ${riskAssessmentData.filter(d => d.riskLevel === 'High').length}
        `;
        triggerDownload(dummyContent, `${fileName}.txt`, 'text/plain');
        resolve();
      }, 1500); // 1.5s delay to simulate server processing
    });
  };

  return (
    <Page title="Reports & Downloads">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card title="Export Data">
          <div className="space-y-4">
            <DownloadItem 
              title="Complete DRR Report" 
              format="PDF Document" 
              icon="📄" 
              onDownload={() => handleMockDownload('India_DRR_Full_Report')}
            />
            <DownloadItem 
              title="Composite Risk Map" 
              format="High-Res PNG" 
              icon="🗺️" 
              onDownload={() => handleMockDownload('Composite_Risk_Map_HiRes')}
            />
            <DownloadItem 
              title="Risk Scores Table" 
              format="CSV File" 
              icon="📊" 
              onDownload={async () => handleCSVDownload()}
            />
            <DownloadItem 
              title="Hazard Layers" 
              format="GeoJSON" 
              icon="🌐" 
              onDownload={async () => handleGeoJSONDownload()}
            />
            <DownloadItem 
              title="Evacuation Routes" 
              format="Shapefile" 
              icon="🛣️" 
              onDownload={() => handleMockDownload('Evacuation_Routes_SHP')}
            />
          </div>
        </Card>
        <Card title="Auto-Generated Report Preview">
            <div className="bg-gray-900 p-4 rounded-lg space-y-4 h-full flex flex-col">
                <div className="flex-grow">
                    <h3 className="text-xl font-bold text-teal-400 border-b border-gray-700 pb-2">India DRR Report: Executive Summary</h3>
                    <div className="text-gray-400 space-y-3 mt-4 text-sm leading-relaxed">
                        <div>
                            <p className="font-semibold text-white">1. Hazard Section</p>
                            <p className="pl-4">Detailed analysis of flood, earthquake, and landslide hazards for selected states including Maharashtra, Tamil Nadu, and Uttarakhand. Data integrated from IMD and GSI sources.</p>
                        </div>
                        <div>
                            <p className="font-semibold text-white">2. Vulnerability Section</p>
                            <p className="pl-4">Assessment of social, economic, and physical vulnerabilities across all {districts.length} districts. Key indicators include housing quality and population density.</p>
                        </div>
                        <div>
                            <p className="font-semibold text-white">3. Risk Prioritization</p>
                            <p className="pl-4">Identification of {riskAssessmentData.filter(d => d.riskLevel === 'High').length} high-risk hotspots requiring immediate attention from state agencies. Priority focus on urban conglomerates.</p>
                        </div>
                        <div>
                            <p className="font-semibold text-white">4. Recommendations</p>
                            <p className="pl-4">Actionable recommendations for mitigation and preparedness aligned with NDMA guidelines, emphasizing early warning system integration.</p>
                        </div>
                    </div>
                </div>
                <div className="pt-4 border-t border-gray-700 text-center">
                    <button 
                        onClick={() => handleMockDownload('Executive_Summary')}
                        className="text-teal-400 hover:text-teal-300 text-sm font-semibold flex items-center justify-center w-full"
                    >
                        <span className="mr-2">🖨️</span> Print Executive Summary
                    </button>
                </div>
            </div>
        </Card>
      </div>
    </Page>
  );
};

export default Reports;
    